### PR TITLE
Use SHA256 hashes for key fingerprints

### LINKED ISSUE #214: Use SHA256 Hash for Key Fingerprints
How would you feel about using the `SHA256` hash instead of the current `MD5` to calculate public key fingerprints?
https://github.com/jpillora/chisel/blob/v1.7.2/share/ccrypto/keys.go#L35

To remain backward compatible we could add a `sha256:` prefix to new fingerprints and evaluate old fingerprints (without the prefix) still as md5 hashes (at least until a new major version would allow the breaking change).

References regarding MD5 deprecation:
* https://tools.ietf.org/id/draft-lvelvindron-tls-md5-sha1-deprecate-01.html

### PR DESCRIPTION
**Pull request by srueg**
Closes #214

### CODE REVIEW

**Comment by jpillora** [comment]
Thanks for the PR though this breaks existing clients using `--fingerprint`

**Comment by jpillora** [comment]
Verification should look for hash outputs like this https://play.golang.org/p/7dSkGjdSNO-

1. 44 chars, ends with `=`, and then base64 decode, verify sha256
1. otherwise, hex decode, verify md5

**Comment by jpillora** [comment]
Also we should update CLI help and docs (mention sha256, undocument md5 hex examples, and support for hash prefixes)

**Comment by srueg** [comment]
Yes, absolutely. Sorry, I wanted to mark the PR as a draft until all the things you mention get implemented.

**Comment by jpillora** [comment]
No worries 👍

**Comment by jpillora** [comment]
PR looks good! Will test soon

**Comment by jpillora** [comment]
Thanks :) Merged and released in `v1.7.3`

**Pull request merged**
