### PR TITLE
Fix missing NetDialContext: c.config.DialContext

### PR DESCRIPTION
**Pull request by GuillaumeSmaha**
Hi,
This line was removed on commit 53e72fe2ba498d654a47a3cedc48ac008aa22638: https://github.com/jpillora/chisel/commit/53e72fe2ba498d654a47a3cedc48ac008aa22638#diff-bd3a55a72186f59e2e63efb4951573b2f9e4a7cc98086e922b0859f8ccc1dd09L220

Thanks for your project

### CODE REVIEW

**Comment by jpillora** [comment]
Thanks yep looks like a bug

**Comment by jpillora** [comment]
I've got a few changes to release but need to upgrade the tests https://github.com/jpillora/chisel/issues/390 are you able to also work on this one :D ?

**Comment by GuillaumeSmaha** [comment]
@jpillora  can you merge this bugfix before the next release ? :)

**Comment by GuillaumeSmaha** [comment]
(rebase the commit)

**Comment by jpillora** [comment]
Merged :)

**Comment by jpillora** [comment]
I was testing a new docker release and squashed `latest` accidentally, so need to do a release now. Don't have much time so 🤞😬

**Pull request merged**
