### PR TITLE
Multi architecture image build

### PR DESCRIPTION
**Pull request by pbstriker38**
Requires docker hub username and access token to be set in this repos Github secrets.

Example of run on my fork: https://github.com/pbstriker38/chisel/runs/1922632641?check_suite_focus=true
Docker images: https://hub.docker.com/r/pbstriker38/chisel/tags?page=1&ordering=last_updated

Closes: #245

### CODE REVIEW

**Comment by jpillora** [comment]
Awesome, thanks Daniel - will test soon

**Comment by jpillora** [comment]
Will tag https://github.com/jpillora/chisel/commit/92d90be68a989377daf61294ef7458612d10da8c to test...

**Comment by jpillora** [comment]
https://github.com/jpillora/chisel/runs/1926911319

**Comment by jpillora** [comment]
Interesting, next run was successful - hopefully that failure is rare... Multi-arch image released:  https://hub.docker.com/repository/docker/jpillora/chisel/tags?page=1&ordering=last_updated thanks again

**Comment by pbstriker38** [comment]
That's odd. Did you try rerunning the 1.7.5 workflow before creating a new tag?

**Pull request merged**
