### PR TITLE
[WIP] Add Support for HTTP/3 and QUIC

### PR DESCRIPTION
**Pull request by zandercodes**
I am in the process of adding `HTTP/3` and `QUIC` support for `chisel`. To make the transfer of `chisel` even faster than it already is.

### CODE REVIEW

**Comment by jpillora** [comment]
Didn’t work?

**Comment by zandercodes** [comment]
> Didn’t work?

The problem is that HTTP/3 uses UDP so it is relatively difficult to implement this because WebSocket is used as a base, which cannot be used under HTTP/3.

**Comment by jpillora** [comment]
Oh yeah, you could skip the WS layer and just run the SSH layer on top of HTTP3?

**Comment by gerardo-junior** [comment]
+1

**Pull request closed without merging**
