### PR TITLE
Add proxy support

### PR DESCRIPTION
**Pull request by chromicant**
Adds support for chisel client to talk over a HTTP proxy.

### CODE REVIEW

**Comment by neutrinus** [comment]
Is there any reason why it's still not merged? I would like to use chisel with proxy... Thank you.

**Comment by jpillora** [comment]
Will try to get this merged soon, just need to find time to test

**Comment by gonsalez-ru** [comment]
Yes, issue is actual.

**Comment by jpillora** [comment]
chisel now has HTTP CONNECT support in `1.2.0`, please update, see `chisel client --help`, test it out and let me know if there are any issues

instead of implementing a custom HTTP CONNECT client like this PR does, I swapped the websockets package to use gorilla which has proxy support built in

**Pull request closed without merging**
