### PR TITLE
Fix #390: Use code to generate certificates for client & server

### LINKED ISSUE #390: Help wanted: Fix tests in go 1.17-19
Help wanted!

At a high level, I want to tests to pass against go1. 17,18,19 in CI

Easy fix, which i'd consider is just to mint modern certs in `test/e2e/tls/` (which don't use x509 common name)

Better fix, in an `init` function in the TLS tests, i'd like to use go's x509/crypto packages to programmatically do the "easy fix" above. the benefit of this is we get certs-as-code which allows us to easily test various TLS settings

Please comment here if you'd like to work on it

### PR DESCRIPTION
**Pull request by GuillaumeSmaha**
I take inspiration from https://go.dev/src/crypto/tls/generate_cert.go to generate the certificate.

`certGetCertificate` allows more complex pattern like generating a CA and signing another certificate with:
```golang

	ca, _ _, err := certGetCertificate(&certConfig{
		isCA: true,
		extKeyUsage: []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
	})

	_, serverCertPEM, serverKeyPEM, err := certGetCertificate(&certConfig{
                signCA: ca
		hosts: []string{
			"0.0.0.0",
			"localhost",
		},
		extKeyUsage: []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
	})
```

I use `ioutil.WriteFile` instead of `os.WriteFile` to be compatible with older go version.

### CODE REVIEW

**Comment by GuillaumeSmaha** [comment]
@jpillora Is it what you looked for ?

**Comment by jpillora** [comment]
Sorry I triggered the tests and then forgot about this PR

Looks good from my phone! Hopefully will get some time tomorrow to look at it properly

Thank you for your work 😁

**Comment by GuillaumeSmaha** [comment]
> Sorry I triggered the tests and then forgot about this PR
> 
> Looks good from my phone! Hopefully will get some time tomorrow to look at it properly
> 
> Thank you for your work grin

Your are welcome. Thanks for building this project :)

**Comment by jpillora** [comment]
Merged :) Thanks again!

**Pull request merged**
